<a href="https://colab.research.google.com/github/JSJeong-me/JBNU-2021/blob/main/Predictive_Analytics/decision_tree/3_1NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

In [14]:
#df = pd.read_csv(".\\Data_USD.csv", header=None,skiprows=1)
df = pd.read_csv("./Data_USD.csv")
#df.head().to_csv(".\\test.csv")

In [ ]:
#T=df.groupby("SEX") 

In [ ]:
#T.describe()

In [ ]:
df.columns

Index(['LIMIT_BAL_US', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_SCORE_AVG',
       'BILL_AVG_US', 'PAY_AMT_AVG_US', 'PAY_TO_BILL', 'CREDIT_UTILIZATION',
       'DEFAULT_PAYMENT_NEXT_MO'],
      dtype='object')

In [ ]:
df.tail()

LIMIT_BAL_US  SEX  EDUCATION  MARRIAGE  AGE  PAY_SCORE_AVG  \
29995   7982.857143    1          3         1   39           0.00   
29996   5442.857143    1          3         2   43          -0.67   
29997   1088.571429    1          2         2   37           1.33   
29998   2902.857143    1          3         1   41          -0.17   
29999   1814.285714    1          2         1   46           0.00   

       BILL_AVG_US  PAY_AMT_AVG_US  PAY_TO_BILL  CREDIT_UTILIZATION  \
29995  4386.634429      257.326190         0.06            0.858855   
29996   128.100667       87.630000         0.68            0.011220   
29997   426.332952      189.290476         0.44            0.118833   
29998  1612.361762      890.094619         0.55           -0.020563   
29999  1396.238000       50.243619         0.04            0.958580   

       DEFAULT_PAYMENT_NEXT_MO  
29995                        0  
29996                        0  
29997                        1  
29998                        1  
29999                        1

In [5]:
# X = df.drop('Y_Value',axis =1).values
# y = df['Y_Value'].values
X = df.drop('DEFAULT_PAYMENT_NEXT_MO',axis =1).values
#X[2999,0]

In [ ]:
X.shape

(30000, 10)

In [6]:
y = df['DEFAULT_PAYMENT_NEXT_MO'].values
#y.reshape(-1,1)

In [ ]:
#print(X.shape)
X.shape

(30000, 10)

In [ ]:
#print(y.shape)
y.shape

(30000,)

In [7]:
X_train, X_test, y_train, y_test = train_test_split (X,y,test_size=0.3, random_state=42)

In [8]:
y_test.T

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_test.shape

(9000, 10)

In [ ]:
df.describe()

LIMIT_BAL_US           SEX     EDUCATION      MARRIAGE           AGE  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean    6077.288279      1.603733      1.853133      1.551867     35.485500   
std     4707.986577      0.489129      0.790349      0.521970      9.217904   
min      362.857143      1.000000      0.000000      0.000000     21.000000   
25%     1814.285714      1.000000      1.000000      1.000000     28.000000   
50%     5080.000000      2.000000      2.000000      2.000000     34.000000   
75%     8708.571429      2.000000      2.000000      2.000000     41.000000   
max    36285.714290      2.000000      6.000000      3.000000     79.000000   

       PAY_SCORE_AVG   BILL_AVG_US  PAY_AMT_AVG_US   PAY_TO_BILL  \
count   30000.000000  30000.000000    30000.000000  30000.000000   
mean       -0.182680   1632.020583      191.415565      0.409982   
std         0.982063   2295.460479      367.862624      7.671398   
min        -2.000000  -2033.566333        0.000000   -546.930000   
25%        -0.830000    173.494095       40.396583      0.040000   
50%         0.000000    763.880810       86.982905      0.100000   
75%         0.000000   2072.074548      202.616405      0.690000   
max         6.000000  31833.959100    22763.637240    797.000000   

       CREDIT_UTILIZATION  DEFAULT_PAYMENT_NEXT_MO  
count        30000.000000             30000.000000  
mean             0.423771                 0.221200  
std              0.411462                 0.415062  
min             -0.619892                 0.000000  
25%              0.022032                 0.000000  
50%              0.313994                 0.000000  
75%              0.829843                 0.000000  
max              6.455300                 1.000000

In [9]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)

In [10]:
X_scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[ 0.56391448,  0.80648893, -1.07681763, ..., -0.49741723,
         0.09035743, -1.02549459],
       [-0.90610925,  0.80648893, -1.07681763, ..., -0.13590122,
         0.08737206, -0.85894506],
       [-0.90610925,  0.80648893,  0.18648797, ..., -0.33785543,
        -0.05294013,  1.2179713 ],
       ...,
       [-0.90610925, -1.23994262, -1.07681763, ..., -0.49741723,
         0.09035743, -1.02549459],
       [-0.75136991,  0.80648893,  0.18648797, ..., -0.31133477,
        -0.05294013,  1.53895893],
       [-0.05504288,  0.80648893,  0.18648797, ..., -0.11985747,
         0.10229889, -1.02579807]])

In [15]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [16]:
y_test_categorical

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [17]:
from keras.models import Sequential

#instantiate
model = Sequential()

In [18]:
from keras.layers import Dense

number_inputs = 10
number_units = 60

model.add(Dense(units = number_units, activation ='relu', input_dim=number_inputs))
model.add(Dense(units = 70, activation ='relu')) #second hidden layer
model.add(Dense(units = 60, activation ='relu')) #second hidden layer
model.add(Dense(units = 50, activation ='relu')) #second hidden layer
model.add(Dense(units = 40, activation ='relu')) #second hidden layer
model.add(Dense(units = 30, activation ='relu')) #second hidden layer
model.add(Dense(units = 20, activation ='relu')) #second hidden layer
model.add(Dense(units = 10, activation ='relu')) #second hidden layer
#model.add(Dense(units = 2, activation ='relu')) #third hidden layer

In [19]:
number_classes =2 ## yes or no
model.add(Dense(units = number_classes, activation = 'sigmoid'))

In [ ]:
model.summary()

In [22]:
#compile the model
model.compile(optimizer = 'adam' ,
             loss = 'binary_crossentropy',
             metrics =['accuracy'])

In [ ]:
#train the model

model.fit(X_train_scaled, y_train_categorical, epochs=50,shuffle = True,verbose =2)

In [ ]:
model.save("12-29-neuralnetwork.h5")

In [24]:
#quantify the model
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test_categorical,verbose =2)
print( model_loss )
print (model_accuracy)

282/282 - 1s - loss: 0.5002 - accuracy: 0.7877
0.5002438426017761
0.7876666784286499


F1, Precision Recall, and Confusion Matrix

In [25]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [26]:
y_prediction = model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [27]:
y_prediction.reshape(-1,1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [29]:
print("Recall score:"+ str(recall_score(y_test, y_prediction)))

Recall score:0.0


In [30]:
print(classification_report(y_test, y_prediction,
                            target_names=["default", "non_default"]))

              precision    recall  f1-score   support

     default       0.78      1.00      0.88      7040
 non_default       0.00      0.00      0.00      1960

    accuracy                           0.78      9000
   macro avg       0.39      0.50      0.44      9000
weighted avg       0.61      0.78      0.69      9000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
import itertools
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="red" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_prediction)
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=['Non_defualt', 'Default'],
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=['Non_defualt', 'Default'], normalize=True,
                      title='Normalized confusion matrix')

plt.show()